### ISSUE TITLE
Feature suggestion: Album filter when adding to queue

### ISSUE THREAD

**Issue by Berjou** [dhonus/jellyfin-tui#18]
Hello. I'm discovering your project and I am really enjoying it so far, thank you for your work!

The only thing bothering me is that, unless I missed something, there is no way to add a whole album (and only the tracks of the selected album) in the queue. Currently, using the latest version of `jellyfin-tui` from the AUR, pressing Enter on an album in the track view adds all the tracks below in the list to the queue, not just the tracks from the album, which seems a little bit counter intuitive to me.

```
❯ jellyfin-tui --version
jellyfin-tui 1.0.3 (libmpv 2.2 131074)
```

I thing it would be a nice feature to have. I did some quick and dirty experiment with the existing code, and it should be possible to use `Song::parent_id` to filter tracks by album in `queue.rs`. Probably adding a new keybinding/config option would be necessary to not break the current behavior.

Regards.

**Comment by dhonus** [comment]
Hi, this feature is on my radar. I just haven't had the time yet :)
You are correct that this is simple to do with just parent_id. The goal would be keep the behavior of adding all the tracks below in the list to the queue when you press Enter on a track, BUT pressing Enter on an album name would add only that album to the queue. The same with the temporary queue (Shift+Enter / 'e').

The implementation itself would really just amount to adding some code to `queue.rs` that `if track.id == "_album_"`, we take the first song of the album and add all following songs with the same parent id.

I'll try to get to it as soon as possible, I've been busy implementing playlist support :)

**Comment by dhonus** [comment]
Fixed in https://github.com/dhonus/jellyfin-tui/releases/tag/v1.0.4
Feel free to reopen if not satisfactory :)
