### ISSUE TITLE
Can't change volume before playing a song

### ISSUE THREAD

**Issue by ondrejhonus** [dhonus/jellyfin-tui#4]
It would be really nice if i had the option to change the music volume before i play a song. When i press +/-, it doesn't change it until i play something.

**Comment by ondrejhonus** [comment]
Also the program crashes when you set the volume over a 1000%.

**Comment by dhonus** [comment]
Fixed in 1e85867bcc5701d3bad8eb32e4b7fa9213a528ab. Volume hard capped at 500%.
